// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkltaefwfpqszceakclg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrbHRhZWZ3ZnBxc3pjZWFrY2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTk1ODgsImV4cCI6MjA3MDI3NTU4OH0.rNFKSyf_wqIjGenqW0D0vo8mWxEjBHaksNveYXsI1cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});